implement touch + fix mouse grab + catch more error
cactorium/glutin pull request #2
Opened 2017-03-29 17:17 UTC by thiolliere

this PR have changed some design:

window have now inner_window field. 
inner_window is accessible in callback through user_data

2017-03-30 04:02 UTC, cactorium requested changes
Thank you for the pull request! Two minor nits though

2017-03-30 04:02 UTC, cactorium commented on src/api/emscripten/mod.rs
>      ffi::EM_FALSE
I'm not expert at emscripten, but should this be `ffi::EM_TRUE` instead?

2017-03-30 04:02 UTC, cactorium commented on src/api/emscripten/mod.rs
> +                    let mut pointerlock_status: ffi::EmscriptenPointerlockChangeEvent = mem::uninitialized();
I wanna say there should be a more memory safe way to do this.. could you please derive `Default` for `EmscriptenPointerlockChangeEvent` and check the return type of `ffi::empscripten_get_pointerlock_status`?

2017-03-30 20:11 UTC, thiolliere commented on src/api/emscripten/mod.rs
>      ffi::EM_FALSE
yes, OK, as we consume event

2017-03-30 20:19 UTC, thiolliere commented on src/api/emscripten/mod.rs
> +                    let mut pointerlock_status: ffi::EmscriptenPointerlockChangeEvent = mem::uninitialized();
yes check result is important.

for default things. if you want to I can do it. but I think it's how this kind of API must be used (https://github.com/thiolliere/glutin/blob/51ce5a3ce9b968db69522746828740836e3203c8/src/api/emscripten/mod.rs#L82-L83)

2017-03-31 15:31 UTC, cactorium commented on src/api/emscripten/mod.rs
> +                    let mut pointerlock_status: ffi::EmscriptenPointerlockChangeEvent = mem::uninitialized();
The weird thing is that get_pointerlock_status can fail, but I think initcontext can't fail? https://kripken.github.io/emscripten-site/docs/api_reference/html5.h.html#c.emscripten_get_pointerlock_status Anyways, the change looks good, thanks!

2017-03-31 15:31 UTC, cactorium approved these changes

2017-03-31 15:32 UTC, merged